--- 
http_interactions: 
- request: 
    method: get
    uri: https://api.github.com/meta
    body: 
      encoding: US-ASCII
      string: ""
    headers: 
      Accept: 
      - application/vnd.github.beta+json
      User-Agent: 
      - Octokit Ruby Gem 2.0.0
      Accept-Encoding: 
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Server: 
      - GitHub.com
      Date: 
      - Tue, 30 Apr 2013 18:18:35 GMT
      Content-Type: 
      - application/json; charset=utf-8
      Transfer-Encoding: 
      - chunked
      Connection: 
      - keep-alive
      Status: 
      - 200 OK
      X-Ratelimit-Limit: 
      - "60"
      X-Ratelimit-Remaining: 
      - "18"
      X-Github-Media-Type: 
      - github.beta; format=json
      X-Content-Type-Options: 
      - nosniff
      Access-Control-Allow-Credentials: 
      - "true"
      Access-Control-Expose-Headers: 
      - Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-OAuth-Scopes, X-Accepted-OAuth-Scopes
      Access-Control-Allow-Origin: 
      - "*"
      Etag: 
      - "\"d8e1f91fc4a69df3834ed0a4bd8f4a73\""
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Vary: 
      - Accept-Encoding
    body: 
      encoding: ASCII-8BIT
      string: "{\"hooks\":[\"207.97.227.253/32\",\"50.57.128.197/32\",\"108.171.174.178/32\",\"50.57.231.61/32\",\"204.232.175.64/27\",\"192.30.252.0/22\"],\"git\":[\"207.97.227.239/32\"]}"
    http_version: 
  recorded_at: Tue, 30 Apr 2013 18:18:36 GMT
recorded_with: VCR 2.4.0
